language: objective-c

osx_image: xcode7.3

install: true

cache:
  directories:
    - $HOME/.cocoapods/

before_script:
- bundle install
#Â - bundle exec pod repo update

notifications:
email:
  on_success: never

script:
- bundle exec fastlane test
